/*
 * Apolonio Villegas Diego Armando
 * Palacios Cabrera Alberto
 * 
 * Práctica 2
 *
 */
	.DEF TMP = R16
	.DEF CONTADOR_FILAS = R17
	.DEF CONTADOR_COLUMNAS = R18
	.CSEG
	.ORG 0

	RJMP CONFIGURACION_PUERTOS
	.ORG $020
	RJMP RECORRER_FILAS

CODIFICACION_FILAS:
	.DB $7F, $BF, $DF, $EF, $F7, $FB, $FD, $FE
CODIFICACION_COLUMNAS_BETO:
	.DB $3C, $7E, $E7, $C3, $FF, $FF, $C3, $C3 ; $4A - $51
CODIFICACION_COLUMNAS_DIEGO:
	.DB $FC, $FE, $C7, $C3, $C3, $C7, $FE, $FC ; $52 - $5A

CONFIGURACION_PUERTOS:
; Puerto B
	LDI TMP, $0F
	OUT DDRB, TMP
; Puerto C
	LDI TMP, $0F
	OUT DDRC, TMP
; Pull-up de C4
	LDI TMP, $10
	OUT PORTC, TMP
; Puerto D
	LDI TMP, $FF
	OUT DDRD, TMP
; Configuración del timer 0
	LDI TMP, $03
	OUT TCCR0B, TMP
	LDI TMP, $01
	STS TIMSK0, TMP
	SEI

	LDI CONTADOR_FILAS, $49

MAIN:
	JMP MAIN

RECORRER_FILAS:
	INC CONTADOR_FILAS
	INC CONTADOR_COLUMNAS
	CPI CONTADOR_FILAS, $4A
	BREQ REINICIAR_CONTADOR
	LDI TMP, $00
	OUT PORTD, TMP
	MOV ZL, CONTADOR_COLUMNAS
	LDI ZH, $00
	LPM TMP, Z
	OUT PORTD, TMP
	MOV ZL, CONTADOR_FILAS
	LDI ZH, $00
	LPM TMP, Z
	ANDI TMP, $0F ; Parte baja filas
	OUT PORTB, TMP
	LPM TMP, Z
	ANDI TMP, $F0 ; Parte alta filas
	LSR TMP
	LSR TMP
	LSR TMP
	LSR TMP
	OUT PORTC, TMP
	RETI

REINICIAR_CONTADOR:
	LDI CONTADOR_FILAS, $41
	IN TMP, PINC
	ANDI TMP, $10
	CPI TMP, $10
	BREQ BETO
	JMP DIEGO

BETO:
	LDI CONTADOR_COLUMNAS, $49
	JMP RECORRER_FILAS

DIEGO:
	LDI CONTADOR_COLUMNAS, $51
	JMP RECORRER_FILAS
