/*
 * Apolonio Villegas Diego Armando
 * Palacios Cabrera Alberto
 * 
 * Práctica 8
 *
 */
    .DEF TEMP = R16
    .DEF LETRAS = R17
    .DEF RENGLON = R18
    .DEF CONT1 = R19
    .DEF CONT2 = R20
    .DEF CONT3 = R21
    .DEF VALOR = R22
    .DEF AUX = R23
    
	.CSEG

    .ORG 0
    JMP RESET

    .ORG $024
    JMP RECIBE

RESET: 
	LDI TEMP, $FE
    OUT DDRD, TEMP
    LDI TEMP, $98 // Se habilita la interrupción de RX y TX
    STS UCSR0B, TEMP
    LDI TEMP, 103 // Baudrate a 9600
    STS UBRR0L, TEMP

	// Configuración de LCD
    CALL DELAY_100M

    LDI TEMP, $28
    OUT PORTD, TEMP // E EN 1, RS EN 0
    LDI TEMP, $20
    OUT PORTD, TEMP // E EN 0, RS EN 0
    CALL DELAY_10M

    LDI TEMP, $28
    OUT PORTD, TEMP // E EN 1, RS EN 0
    LDI TEMP, $20
    OUT PORTD, TEMP // E EN 0, RS EN 0
    
    LDI TEMP, $88
    OUT PORTD, TEMP // E EN 1, RS EN 0
    LDI TEMP, $80
    OUT PORTD, TEMP // E EN 0, RS EN 0
    CALL DELAY_10M

    //DISPLAY ON-OF

    LDI TEMP, $08
    OUT PORTD, TEMP // E EN 1, RS EN 0
    LDI TEMP, $00
    OUT PORTD, TEMP // E EN 0, RS EN 0
    
    LDI TEMP, $E8
    OUT PORTD, TEMP // E EN 1, RS EN 0
    LDI TEMP, $E0
    OUT PORTD, TEMP // E EN 0, RS EN 0
    CALL DELAY_10M

    //ENTRY MODE

    LDI TEMP, $08
    OUT PORTD, TEMP // E EN 1, RS EN 0
    LDI TEMP, $00
    OUT PORTD, TEMP // E EN 0, RS EN 0

    LDI TEMP, $68
    OUT PORTD, TEMP // E EN 1, RS EN 0
    LDI TEMP, $60
    OUT PORTD, TEMP // E EN 0, RS EN 0
    CALL DELAY_10M
    
    //CLEAR DISPLAY
    LDI TEMP, $08
    OUT PORTD, TEMP // E EN 1, RS EN 0
    LDI TEMP, $00
    OUT PORTD, TEMP // E EN 0, RS EN 0
   
    LDI TEMP, $18
    OUT PORTD, TEMP // E EN 1, RS EN 0
    LDI TEMP, $10
    OUT PORTD, TEMP // E EN 0, RS EN 0
    CALL DELAY_10M

    LDI LETRAS,$00
    LDI RENGLON,$01
	
    SEI

MAIN: 
    JMP MAIN

RECIBE: 
	LDS VALOR, UDR0
	CPI LETRAS, 16
    BREQ CAMBIAR_RENGLON
    CPI LETRAS, 32
    BREQ CLEARDISPLAY
    JMP CARGAR_VALOR

CAMBIAR_RENGLON:
    LDI TEMP, $C8
    OUT PORTD, TEMP // E EN 1, RS EN 0
    LDI TEMP, $C0
    OUT PORTD, TEMP // E EN 0, RS EN 0
    CALL DELAY_10M

    LDI TEMP, $08
    OUT PORTD, TEMP // E EN 1, RS EN 0
    LDI TEMP, $00
    OUT PORTD, TEMP // E EN 0, RS EN 0
    CALL DELAY_10M
    
    JMP CARGAR_VALOR

CLEARDISPLAY:
	LDI TEMP, $08
    OUT PORTD, TEMP // E EN 1, RS EN 0
    LDI TEMP, $00
    OUT PORTD, TEMP // E EN 0, RS EN 0
    CALL DELAY_10M

    LDI TEMP, $18
    OUT PORTD, TEMP // E EN 1, RS EN 0
    LDI TEMP, $10
    OUT PORTD, TEMP // E EN 0, RS EN 0
    CALL DELAY_10M

    LDI LETRAS,$00
    JMP CARGAR_VALOR

CARGAR_VALOR:
	MOV AUX,VALOR 
    ANDI AUX,$F0
    ORI AUX, $0C
    OUT PORTD, AUX
    ANDI AUX,$F0
    ORI AUX, $04
    OUT PORTD, AUX
    
    MOV AUX,VALOR 
    ANDI AUX,$0F
    LSL AUX
    LSL AUX
    LSL AUX
    LSL AUX
    ORI AUX, $0C
    OUT PORTD, AUX
    ANDI AUX,$F0
    ORI AUX, $04
    OUT PORTD, AUX
    CALL DELAY_10M

    INC LETRAS
    RETI


DELAY_100M:
	LDI	CONT1, 4
LAZO3:	
	LDI	CONT2, 200
LAZO2:	
	LDI	CONT3, 200
LAZO1:
	NOP
	NOP
	NOP
	NOP
	NOP
	NOP
	NOP
	DEC	CONT3
	BRNE LAZO1
	DEC CONT2
	BRNE LAZO2
	DEC CONT1
	BRNE LAZO3
	RET

DELAY_10M:
	LDI	CONT1, 80
LAZO5:	
	LDI	CONT2, 200
LAZO4:
	NOP
	NOP
	NOP
	NOP
	NOP
	NOP
	NOP
	DEC	CONT2
	BRNE LAZO4
	DEC CONT1
	BRNE LAZO5
	RET
